'use strict';

module.exports = {
    DEFAULT_SERVER_IP: "0.0.0.0",
    DEFAULT_SERVER_PORT: 12345,

    DEFAULT_MONGODB_HOST: "localhost",
    DEFAULT_MONGODB_PORT: 27017,
    DEFAULT_MONGODB_DATABSE: "radathina",

    DEFAULT_NEARBY_RADIUS_M: 1000,

    EARTH_RADIUS_M: 6371000
}